name: Run Shell Script on EC2 Instance
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Script on EC2 Instance
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Change to the directory where the script is located
            cd /home/${{ secrets.USER }}/blur

            git pull
            # Make the script executable
            chmod +x deploy.sh

            # Run the script
            ./deploy.sh
